# DO NOT EDIT — generated by packages/schema/codegen/to_python.ts.
# Regenerate with: pnpm --filter @arcana/schema codegen
# Drift is caught by: pnpm --filter @arcana/schema codegen:check
#
# Sources: packages/schema/src/*.ts (UIBlock + payloads + api + entities).
# Wire-contract invariant: R-10, NFR-MNT-02, NFR-SEC-04 (validate.py).

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class BlockMeta(BaseModel):
    panel: Panel
    order: float
    status: BlockStatus


class BlurtingPrompt(BaseModel):
    type: Literal['BlurtingPrompt']
    id: str
    meta: BlockMeta
    data: BlurtingPromptData


class BlurtingPromptData(BaseModel):
    topic: str
    prompt: str
    sourcePassage: str
    citations: list[Citation]


class ChatMessage(BaseModel):
    role: ChatRole
    content: str


class ChatRequest(BaseModel):
    notebookId: str
    message: str
    history: list[ChatMessage]
    activeMode: Mode | None = None


class Chunk(BaseModel):
    id: str
    docId: str
    text: str
    page: float | None


class Citation(BaseModel):
    id: str
    docId: str
    docTitle: str
    page: float | None
    quote: str


class CitedSummary(BaseModel):
    type: Literal['CitedSummary']
    id: str
    meta: BlockMeta
    data: CitedSummaryData


class CitedSummaryData(BaseModel):
    summary: str
    segments: list[SummarySegment]
    citations: list[Citation]


class ContradictingClaim(BaseModel):
    docId: str
    docTitle: str
    stance: str
    quote: str


class ContradictionAlert(BaseModel):
    type: Literal['ContradictionAlert']
    id: str
    meta: BlockMeta
    data: ContradictionAlertData


class ContradictionAlertData(BaseModel):
    concept: str
    summary: str
    claims: list[ContradictingClaim]


class CornellNote(BaseModel):
    cue: str
    content: str
    citationIds: list[str]


class CornellNotes(BaseModel):
    type: Literal['CornellNotes']
    id: str
    meta: BlockMeta
    data: CornellNotesData


class CornellNotesData(BaseModel):
    topic: str
    notes: list[CornellNote]
    summary: str
    citations: list[Citation]


class DocListResponse(BaseModel):
    docs: list[DocStatusResponse]


class DocStatusResponse(BaseModel):
    docId: str
    title: str
    sourceUri: str
    status: Literal['pending', 'parsing', 'embedding', 'ready', 'failed']
    sizeBytes: float
    error: str | None
    createdAt: str


class Document(BaseModel):
    id: str
    title: str
    sourceUri: str
    ingestStatus: IngestStatus


class DraftEditor(BaseModel):
    type: Literal['DraftEditor']
    id: str
    meta: BlockMeta
    data: DraftEditorData


class DraftEditorData(BaseModel):
    title: str
    sections: list[DraftSection]
    citations: list[Citation]
    wordCount: float


class DraftSection(BaseModel):
    heading: str
    body: str
    citationIds: list[str]


class DueCard(BaseModel):
    cardId: str
    front: str
    topic: str
    dueAt: str
    intervalDays: float
    overdue: bool


class FeedbackRating(BaseModel):
    sessionId: str
    blockId: str
    userId: str
    rating: Literal['up', 'down']
    blockType: str
    timestamp: str


class FeynmanExplainer(BaseModel):
    type: Literal['FeynmanExplainer']
    id: str
    meta: BlockMeta
    data: FeynmanExplainerData


class FeynmanExplainerData(BaseModel):
    concept: str
    explanation: str
    gaps: list[str]
    source: Citation


class Flashcard(BaseModel):
    front: str
    back: str
    source: Citation
    schedule: ScheduleState | None


class FlashcardDeck(BaseModel):
    type: Literal['FlashcardDeck']
    id: str
    meta: BlockMeta
    data: FlashcardDeckData


class FlashcardDeckData(BaseModel):
    topic: str
    cards: list[Flashcard]
    totalCards: float
    dueCount: float


class GapAnalysis(BaseModel):
    type: Literal['GapAnalysis']
    id: str
    meta: BlockMeta
    data: GapAnalysisData


class GapAnalysisData(BaseModel):
    summary: str
    gaps: list[KnowledgeGap]
    coveredTopics: list[str]


class GraphEdge(BaseModel):
    source: str
    target: str
    relation: str


class GraphNode(BaseModel):
    id: str
    label: str
    nodeType: str


class IngestResponse(BaseModel):
    docId: str
    title: str
    status: Literal['ready', 'failed']
    chunkCount: float
    error: str | None


class InsightCard(BaseModel):
    type: Literal['InsightCard']
    id: str
    meta: BlockMeta
    data: InsightCardData


class InsightCardData(BaseModel):
    insight: str
    connection: str
    docAId: str
    docATitle: str
    docBId: str
    docBTitle: str
    citations: list[Citation]


class KnowledgeGap(BaseModel):
    label: str
    description: str
    severity: GapSeverity


class KnowledgeGraphView(BaseModel):
    type: Literal['KnowledgeGraphView']
    id: str
    meta: BlockMeta
    data: KnowledgeGraphViewData


class KnowledgeGraphViewData(BaseModel):
    nodes: list[GraphNode]
    edges: list[GraphEdge]
    focusNodeId: str | None = None


class LiteratureMatrix(BaseModel):
    type: Literal['LiteratureMatrix']
    id: str
    meta: BlockMeta
    data: LiteratureMatrixData


class LiteratureMatrixData(BaseModel):
    query: str
    dimensions: list[str]
    rows: list[MatrixRow]
    citations: list[Citation]


class MatrixCell(BaseModel):
    text: str
    citationId: str | None


class MatrixRow(BaseModel):
    docId: str
    docTitle: str
    cells: list[MatrixCell]


class Notebook(BaseModel):
    id: str
    userId: str
    title: str
    createdAt: str
    updatedAt: str
    docCount: float


class NotebookCreate(BaseModel):
    title: str


class NotebookDeleteResponse(BaseModel):
    deleted: str


class NotebookItem(BaseModel):
    id: str
    userId: str
    title: str
    createdAt: str
    updatedAt: str
    docCount: float


class NotebookListResponse(BaseModel):
    notebooks: list[NotebookItem]


class QuizCard(BaseModel):
    type: Literal['QuizCard']
    id: str
    meta: BlockMeta
    data: QuizCardData


class QuizCardData(BaseModel):
    question: str
    questionType: QuizType
    options: list[QuizOption]
    correctIndex: float | None
    explanation: str
    difficulty: QuizDifficulty
    source: Citation


class QuizOption(BaseModel):
    index: float
    text: str


class ReviewRequest(BaseModel):
    cardId: str
    rating: ReviewRating


class ReviewResponse(BaseModel):
    cardId: str
    dueAt: str
    interval: float
    easeFactor: float
    repetitions: float


class ScheduleState(BaseModel):
    dueAt: str
    interval: float
    easeFactor: float
    repetitions: float


class SocraticDialog(BaseModel):
    type: Literal['SocraticDialog']
    id: str
    meta: BlockMeta
    data: SocraticDialogData


class SocraticDialogData(BaseModel):
    concept: str
    turns: list[SocraticTurn]
    nextQuestion: str
    bloomLevel: BloomLevel


class SocraticTurn(BaseModel):
    role: SocraticRole
    text: str


class StudyPlanner(BaseModel):
    type: Literal['StudyPlanner']
    id: str
    meta: BlockMeta
    data: StudyPlannerData


class StudyPlannerData(BaseModel):
    notebookId: str
    dueCards: list[DueCard]
    totalDue: float
    overdueCount: float
    nextSessionAt: str | None
    sessionGoal: float


class SummarySegment(BaseModel):
    text: str
    citationIds: list[str]


class SurveySubmission(BaseModel):
    sessionId: str
    userId: str
    timestamp: str
    responses: list[float]
    susScore: float
    taskDescription: str


class TurnEvent(BaseModel):
    sessionId: str
    userId: str
    timestamp: str
    query: str
    mode: Mode
    intent: str
    agentsTriggered: list[str]
    latencyMs: float
    blockTypes: list[str]
    retrievedChunkCount: float


class UrlIngestRequest(BaseModel):
    url: str
    notebookId: str | None = None


class UserPreferences(BaseModel):
    defaultMode: str
    theme: str


class UserProfile(BaseModel):
    uid: str
    email: str | None
    displayName: str | None
    createdAt: str
    preferences: UserPreferences


BlockStatus = Literal['loading', 'partial', 'ready', 'error']

BloomLevel = Literal['recall', 'comprehension', 'application', 'analysis', 'synthesis', 'evaluation']

ChatRole = Literal['user', 'assistant']

GapSeverity = Literal['high', 'medium', 'low']

IngestStatus = Literal['pending', 'parsing', 'embedding', 'ready', 'failed']

Mode = Literal['research', 'study', 'writing', 'socratic', 'exploration']

Panel = Literal['sources', 'chat', 'studio']

QuizDifficulty = Literal['recall', 'comprehension', 'application', 'analysis']

QuizType = Literal['mcq', 'short_answer']

ReviewRating = float

SocraticRole = Literal['tutor', 'learner']

UIBlock = Annotated[CitedSummary | LiteratureMatrix | ContradictionAlert | GapAnalysis | InsightCard | KnowledgeGraphView | FlashcardDeck | QuizCard | SocraticDialog | FeynmanExplainer | DraftEditor | StudyPlanner | BlurtingPrompt | CornellNotes, Field(discriminator='type')]
