# DO NOT EDIT — generated by packages/schema/codegen/to_python.ts.
# Regenerate with: pnpm --filter @arcana/schema codegen
# Drift is caught by: pnpm --filter @arcana/schema codegen:check
#
# Sources: packages/schema/src/*.ts (UIBlock + payloads + api + entities).
# Wire-contract invariant: R-10, NFR-MNT-02, NFR-SEC-04 (validate.py).

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class BlockMeta(BaseModel):
    panel: Panel
    order: int
    status: BlockStatus


class ChatMessage(BaseModel):
    role: ChatRole
    content: str


class ChatRequest(BaseModel):
    notebookId: str
    message: str
    history: list[ChatMessage]


class Chunk(BaseModel):
    id: str
    docId: str
    text: str
    page: int | None


class Citation(BaseModel):
    id: str
    docId: str
    docTitle: str
    page: int | None
    quote: str


class CitedSummary(BaseModel):
    type: Literal['CitedSummary']
    id: str
    meta: BlockMeta
    data: CitedSummaryData


class CitedSummaryData(BaseModel):
    summary: str
    segments: list[SummarySegment]
    citations: list[Citation]


class Document(BaseModel):
    id: str
    title: str
    sourceUri: str
    ingestStatus: IngestStatus


class SummarySegment(BaseModel):
    text: str
    citationIds: list[str]


BlockStatus = Literal['loading', 'partial', 'ready', 'error']

ChatRole = Literal['user', 'assistant']

IngestStatus = Literal['pending', 'parsing', 'embedding', 'ready', 'failed']

Panel = Literal['sources', 'chat', 'studio']

UIBlock = CitedSummary
