"""Public block types - the stable import surface for UI blocks.

Re-exports the generated Pydantic models so callers can use a stable
import path (`from api.genui.blocks import CitedSummary`) without
reaching into the underscore-prefixed `_generated.py`. The generated
module is regenerated by `pnpm --filter @arcana/schema codegen`; this
file's contents follow whatever the schema currently exposes.
"""

from __future__ import annotations

from api.genui._generated import (
    BlockMeta,
    BlockStatus,
    ChatMessage,
    ChatRequest,
    ChatRole,
    Chunk,
    Citation,
    CitedSummary,
    CitedSummaryData,
    Document,
    IngestStatus,
    Panel,
    SummarySegment,
    UIBlock,
)

__all__ = [
    "BlockMeta",
    "BlockStatus",
    "ChatMessage",
    "ChatRequest",
    "ChatRole",
    "Chunk",
    "Citation",
    "CitedSummary",
    "CitedSummaryData",
    "Document",
    "IngestStatus",
    "Panel",
    "SummarySegment",
    "UIBlock",
]
