"""GET /suggestions — seed questions from the ingested corpus (§7.1 activation flow).

Returns up to 3 cross-document research questions generated by the LLM from
document titles in the corpus. Cached for _TTL_SECONDS so page loads don't
hammer the model. Returns [] when no documents have been ingested yet.
"""

from __future__ import annotations

import json
import re
import time

from fastapi import APIRouter, Request

from api.core.logging import get_logger

logger = get_logger(__name__)

router = APIRouter()

_TTL_SECONDS = 300.0

_cache: dict = {"suggestions": [], "ts": 0.0, "doc_count": 0}

_SYSTEM = (
    "You are an academic research assistant. "
    "Given a list of document titles, generate exactly 3 short research questions "
    "that invite cross-document comparison, synthesis, or contradiction. "
    "Respond ONLY with a JSON array of 3 strings, e.g. [\"Q1\", \"Q2\", \"Q3\"]. "
    "No prose, no explanation — only the JSON array."
)


async def _generate(titles: list[str], llm) -> list[str]:
    from api.llm.types import Message

    body = "\n".join(f"- {t}" for t in titles)
    try:
        raw = await llm.complete(
            [Message(role="user", content=f"Documents:\n{body}\n\nGenerate 3 research questions.")],
            system=_SYSTEM,
        )
        m = re.search(r"\[.*\]", raw.strip(), re.DOTALL)
        if m:
            parsed = json.loads(m.group(0))
            if isinstance(parsed, list):
                return [str(q) for q in parsed[:3]]
    except Exception:
        logger.warning("suggestions.generate_failed")
    return []


@router.get("/suggestions")
async def get_suggestions(request: Request) -> dict:
    """Return up to 3 seed research questions from the ingested corpus."""
    shared = getattr(request.app.state, "shared", None)
    if not shared:
        return {"suggestions": []}

    doc_store = shared.get("doc_store")
    llm = shared.get("llm")
    if not doc_store or not llm:
        return {"suggestions": []}

    docs = await doc_store.list_documents()
    if not docs:
        return {"suggestions": []}

    now = time.monotonic()
    doc_count = len(docs)
    if (
        _cache["suggestions"]
        and (now - _cache["ts"]) < _TTL_SECONDS
        and _cache["doc_count"] == doc_count
    ):
        return {"suggestions": _cache["suggestions"]}

    titles = [d.title for d in docs[:10]]
    suggestions = await _generate(titles, llm)

    _cache.update({"suggestions": suggestions, "ts": now, "doc_count": doc_count})
    return {"suggestions": suggestions}
